### ISSUE TITLE
Specification of evoQuiz

### ISSUE THREAD

**Issue by ldallos** [ldallos/evoQuiz#1]
Sziasztok!

Sok minden infót össze kell szednünk ahhoz, hogy el tudjuk kezdeni az idei evoQuiz nevezetű projectünket. A legelső ilyen az lenne, hogy a gitHub-os kommunikációt milyen nyelven szeretnétek? 
**Magyarul vagy angolul?**
Kérlek válasszatok.

**Comment by kovacsgabor55** [comment]
Szerintem jó lesz magyarul.

**Comment by Tsanad** [comment]
kevesen vagyunk, és második nyelvként nem mindenki angolt tanult, legyen magyar

**Comment by Hupcsi** [comment]
Magyar :D

**Comment by ldallos** [comment]
Nahát akkor 3-an szóltatok a magyar mellett, egy tartózkodás volt.
Így akkor kijelentem, hogy magyarul fogunk itt írni.
